### ISSUE TITLE
容器化部署&测试

### ISSUE THREAD

**Issue by EricJeffrey** [EricJeffrey/Lab418Site#4]
容器化部署可以更直观看到效果。另外，需要一些`可行性保证`的测试。

**Comment by EricJeffrey** [comment]
目前来看可能需要使用`docker-compose`实现容器化部署，MySQL和redis这俩应该需要单独的容器才能运行。
[参考连接](https://stackoverflow.com/a/28793879/9391860)

另外dockerhub上也有jdk12的镜像
![image](https://user-images.githubusercontent.com/33823695/89652389-fe1c2300-d8f7-11ea-80a0-176f44bc0f5e.png)

**Comment by EricJeffrey** [comment]
服务程序dockerfile:

```dockerfile
FROM openjdk:12.0.1-jdk-oracle
# server jar here
COPY Main.class /lab418site/
WORKDIR /lab418site/
CMD [ "java", "Main" ]
```
docker-compose文件:
```yml
version: "3"
services: 
    mysql:
        image: "mysql:latest"
        # password here
        environment: MYSQL_ROOT_PASSWORD=123456
        environment: MYSQL_DATABASE=lab418
    redis:
        image: "redis:alpine"
    webapp:
        build:
            dockerfile: server.dockerfile
        ports: 
            8080:8001
```

如果没有问题的话，后续
1. 修改后端与mysql，redis的连接地址
2. 打包成jar或其他可执行格式，拷贝到容器中执行

**Comment by EricJeffrey** [comment]
MySQL需要一个.sql文件创建表，所以也需要dockerfile做镜像了，目前

docker-compose.yml:
```yml
version: "3"
services: 
    mysql:
        build: 
            dockerfile: mysql.dockerfile
    redis:
        image: "redis:alpine"
    webapp:
        build:
            dockerfile: server.dockerfile
        ports: 
            8080:8001
        
```

mysql.dockerfile:
```dockerfile
FROM mysql:5.7

# 应该与sql文件中的密码一致
ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=lab418
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=123456

# 会自动执行
COPY ./startup.sql /docker-entrypoint-initdb.d

# 没什么用，需要在run或者compose里面再配置
EXPOSE 3306
# charset
CMD [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
```
startup.sql
```sql
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' identified BY '123456' WITH GRANT OPTION;
CREATE TABLE IF NOT EXISTS halo(
   id INT UNSIGNED AUTO_INCREMENT,
   title TEXT,
   PRIMARY KEY ( id )
)CHARSET=utf8;

INSERT INTO halo ( title )
VALUES
( '测试标题1' );
INSERT INTO halo ( title )
VALUES
( '测试标题2' );

SELECT * from halo;
```
以及server.dockerfile
```dockerfile
FROM openjdk:12.0.1-jdk-oracle
# todo server jar here
COPY Main.class /lab418site/
WORKDIR /lab418site/
CMD [ "java", "Main" ]

```
